<!-- Testimonials data 1 -->
<script>
  const testimonials1 = [
  { name: "Xiyl Mal", server: "Raiden", text: "great place, great people, great jump puzzles!" },
  { name: "Mallesa Tesanu", server: "Cerberus", text: "Great place and well done with a cool idea ♥" },
  { name: "Michi Edelgard", server: "Ragnarok", text: "smol chinken worked here" },
  { name: "Sehnsucht Immer", server: "Alpha", text: "10/10 ordered fish n chips" },
  { name: "Sipher Ous", server: "Sagittarius", text: "You have built something beautiful. Perfect match to the hostess, and I fell for her all over again." },
  { name: "Pinczu Shiro", server: "Ragnarok", text: "Cute place i recomend it" },
  { name: "Valkyrie Silver", server: "Louisoix", text: "Good drinks, good fights, lost my soul, 10/10." },
  { name: "Yui Dotharl", server: "Phantom", text: "Because of this fine venue I had a pleasure being judge on the glorious Bo3 duel in Wolf's den!" },
  { name: "Pomhub Ceo", server: "Sagittarius", text: "nice floor" },
  { name: "Lumi Kuu", server: "Spriggan", text: "Nicest looking place for a while. Love the atmosphere ♥" },
  { name: "Kiki Ze'niki", server: "Raiden", text: "Best venue I have seen in a long time! Awesome vibes, wonderful design, great concept! Moon & Kiki xoxo" },
  { name: "Renarin Storm", server: "Sagittarius", text: "Thanks for the JP, I beat it first time, only took a few seconds to reach the top!" },
  { name: "Heidi Farron", server: "Louisoix", text: "This place is awsome. I need those bat pumpkins" },
  { name: "Vex Sephtis", server: "Zodiark", text: "WOW! Really nice decorations :3" },
  { name: "Thirion Tritonia", server: "Zodiark", text: "Such a lovely place!!! <3" },
  { name: "Mini'bob Ross", server: "Zodiark", text: "*can't reach the book properly!* *illegible scribblings*" },
  { name: "Elle Kanza", server: "Moogle", text: "Awesome decoration, amazing vibes, great place :D" },
  { name: "Erya Valya", server: "Sagittarius", text: "Great atmosphere, amazing job with the decoration, I hope everyone keeps having fun in here ♥" },
  { name: "Pomhub Ceo", server: "Sagittarius", text: "nice bar" },
  { name: "Vanc Angel", server: "Raiden", text: "Stunning location, beautiful gose location! ^_^ ♥" },
  { name: "Jasmine Draconia", server: "Alpha", text: "lovely (: i enjoyed the jumping puzzle. n the bartenders are funny" },
  { name: "Fis Herman", server: "Louisoix", text: "The effort that is seen in this house is really worth every praise. From the decor to the puzzles, all rounded up with great people inside. 10/10" },
  { name: "Catbosylim Smash", server: "Louisoix", text: "One of the most beautiful venues I've seen. Nice hosts and interesting puzzles. I'll be back B)" },
  { name: "Lorilae Lesrekta", server: "Sagittarius", text: "love to be here. I had to lose my girlfriend in the bottomless pit, but it's OK" },
  { name: "Selina Eileen", server: "Sagittarius", text: "Nice location ; )" },
  { name: "Barinn Thensi", server: "Ragnarok", text: "very nice place! great place to relax. will be coming back!" },
  { name: "Peach'n Raspberry", server: "Zodiark", text: "HAS BIG FISHIES! FISHIES ARE SCARY!! Drinks are good, bar staff are nice. But no to the fishies!!!!!!! :(" },
  { name: "Aniki Bob", server: "Sagittarius", text: "I live nearby and I didn't know we had this! Stock prices go vroooooooooom" },
  { name: "Il Ya", server: "Sagittarius", text: "Best venue I've ever seen hands down!" },
  { name: "Papsu Papsu", server: "Spriggan", text: "Waaaaa" },
  { name: "Prince Samael", server: "Spriggan", text: "lovely establishment, congratulations with the grand opening :)" },
  { name: "Patrick Yaeger", server: "Zodiark", text: "Love the design :)" },
  { name: "Lucie Lionheart", server: "Twintania", text: "Awesome atmosphere and people <3" },
  { name: "Rose Lovelace", server: "Twintania", text: "Very adorable place" },
  { name: "Lilimarie Fla'me", server: "Louisoix", text: "Nice party. Thank you for the invite. Much love! <3" },
  { name: "Prin Talino", server: "Phantom", text: "Cozy, Enjoyable, and a Parkour worth looking into." },
  { name: "Freyja Moonlight", server: "Phantom", text: "Very cozy and cute! <3" },
  { name: "Dreamful Alice", server: "Spriggan", text: "Club tiki drinks are freeeeee! Fun and sunshine theres enough for everyone! all thats missing is the sea :( but dont worry, you can sun tan!" },
  { name: "Desya Ilyich", server: "Sagittarius", text: "Best tiki bar aaaaah!" },
  { name: "Meiko Chu", server: "Louisoix", text: "Stuck in stairs, broke both legs :<" },
  { name: "Jynxxie O'haii", server: "Omega", text: "Beautiful bar, amazing atmosphere! ♥" },
  { name: "Yaropol Asvana", server: "Omega", text: "10/10 would visit the void again. (it's pretty cosy)" },
  { name: "Bep Toot", server: "Odin", text: "beautifullllllllll" },
  { name: "Cocoa Powder", server: "Omega", text: "woaah!! sick design ♥" },
  { name: "Secrov Stardream", server: "Odin", text: "Lovely, place and lovely people. What more can one ask for?" },
  { name: "Kittynub Ragstara", server: "Zodiark", text: "Really cute tiki bar! 10/10 design! ❤️❤️❤️❤️❤️" },
  { name: "Siandr Mandragor", server: "Moogle", text: "Well done! :) The Tiki Bar is a great place :)" },
  { name: "Rapsus Ackus", server: "Cerberus", text: "Rapsus war hier" },
  { name: "Xora Chi", server: "Phoenix", text: "Amzinngg woorkk !!! I love it <3" },
  { name: "Celna Vopisel", server: "Sagittarius", text: "I love how the place turn up, keep up good work!" },
  { name: "Zinger Kay-effcee", server: "Sagittarius", text: "Nice place, but no vodka ;^;" },
  { name: "Kuva Bowbringer", server: "Sagittarius", text: "9/10, point pending when vodka is restocked" },
  { name: "Marcelene Minara", server: "Sagittarius", text: "So pretty <3" },
  { name: "Lolo Wololo", server: "Phantom", text: "\\o/" },
  { name: "Palchinett Fyllistine", server: "Omega", text: "Cozy bar is a cool bar!" },
  { name: "Oz Polaris", server: "Omega", text: "It's quite a cute bar" },
  { name: "Isiah Panda", server: "Sagittarius", text: "Really lovely ^_^ good job :D" },
  { name: "Baron Volfas", server: "Ragnarok", text: "Amazing Place you did really great work !! ♥" },
  { name: "K'ricket Sweetvale", server: "Ragnarok", text: "Best tiki bar I've ever seen in or out of Eorzea!" },
  { name: "Artelies Fwall", server: "Odin", text: "This is amazing!!! Truly, one of the best places around :D! Well done!" },
  { name: "Abtgr Meatlusch", server: "Sagittarius", text: "Great !!!!" },
  { name: "Lilly Rosewood", server: "Sagittarius", text: "WOW I'm impressed <3" }
  ];
  </script>
